# Generated by Django 2.2.1 on 2019-05-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_auto_20190525_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
    ]
