# Generated by Django 2.2.1 on 2019-05-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_remove_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[(1, 'To do'), (2, 'Doing'), (3, 'Done')], default=1, max_length=6),
        ),
    ]
