# Generated by Django 2.2.1 on 2019-05-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_auto_20190526_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='2019-06-26'),
        ),
    ]
