# Generated by Django 2.2.1 on 2019-05-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_auto_20190526_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
