# Generated by Django 2.2.1 on 2019-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0009_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('TO_DO', 'To do'), ('DOING', 'Doing'), ('DONE', 'Done')], default=1, max_length=6),
        ),
    ]
